import React, { useMemo } from 'react'

// Fun loading phrases
const LOADING_PHRASES = [
  "Accomplishing",
  "Actioning",
  "Actualizing",
  "Ally-ifying",
  "Baking",
  "Brewing",
  "Calculating",
  "Cerebrating",
  "Churning",
  "Coalescing",
  "Cogitating",
  "Computing",
  "Conjuring",
  "Considering",
  "Cooking",
  "Crafting",
  "Creating",
  "Crunching",
  "Deliberating",
  "Determining",
  "Doing",
  "Effecting",
  "Finagling",
  "Forging",
  "Forming",
  "Generating",
  "Hatching",
  "Herding",
  "Honking",
  "Hustling",
  "Ideating",
  "Inferring",
  "Manifesting",
  "Marinating",
  "Moseying",
  "Mulling",
  "Mustering",
  "Musing",
  "Noodling",
  "Percolating",
  "Pondering",
  "Processing",
  "Puttering",
  "Reticulating",
  "Ruminating",
  "Schlepping",
  "Shucking",
  "Simmering",
  "Smooshing",
  "Spinning",
  "Stewing",
  "Synthesizing",
  "Thinking",
  "Transmuting",
  "Vibing",
  "Working",
  "Fixing",
  "Reckoning",
  "Studying",
  "Visiting",
  "Tarrying",
  "Dawdling",
  "Dallying",
  "Lollygagging",
  "Meandering",
  "Ambling",
  "Sauntering",
  "Savoring",
  "Lingering",
  "Setting-a-spell",
  "Bless-your-hearting",
  "Sweetening",
  "Honeying",
  "Charming",
  "Neighboring",
  "Porch-swinging",
  "Sweet-tea-sipping",
  "Pecan-shelling",
  "Buttermilking",
  "Biscuit-baking",
  "Front-porching",
  "Fretting",
  "Recollecting",
  "Synaptifying",
  "Brainulating",
  "Thoughtinating",
  "Logicking",
  "Neuronifying",
  "Clevering",
  "Wisdomizing",
  "Geniusing",
  "Smartifying",
  "Brilliancing",
  "Pixel-wrangling",
  "Bit-shuffling",
  "Byte-herding",
  "Code-whispering",
  "Quantum-entangling",
  "Data-massaging",
  "Neural-networking",
  "Caffeinating",
  "Espresso-shotting",
  "Buffering",
  "Syncing",
  "Tokenizing",
  "Vectorizing",
  "Embeddifying",
  "Promptinating",
  "Transformerizing",
  "Gradient-descending",
  "Convoluting",
  "Encodifying",
  "Decodifying",
  "Latent-spacing",
  "Fine-tuning",
  "Chain-of-thoughting",
  "Beamsearching",
  "Spline-reticulating",
  "Flux-capacitating",
  "Warp-driving",
  "Hyperspace-jumping",
  "Jiggawatting",
  "Time-looping",
  "Multiversing",
  "Dimensioning",
  "Sorcering",
  "Wizarding",
  "Alchemizing",
  "Potion-brewing",
  "Spell-casting",
  "Incantating",
  "Enchantifying",
  "Prestidigitating",
  "Abracadabra-ing",
  "Hocus-pocusing",
  "Presto-changing",
  "Kazam-ing",
  "Whimsy-ing",
  "Shenaniganning",
  "Tomfoolering",
  "Bamboozling",
  "Flibbertigibbetting",
  "Cattywampusing",
  "Discombobulating",
  "Hullaballooning",
  "Rigmaroling",
  "Kerfuffling",
  "Hulk-smashing",
  "Vibranium-vibrating",
  "Thanos-snapping",
  "Infinity-stoning",
  "Mjolnir-summoning",
  "Web-slinging",
  "Shield-throwing",
  "Stark-teching",
  "Arc-reactoring",
  "Repulsor-blasting",
  "Asgard-bifrosting",
  "Multiversing-of-madness",
  "Pym-particling",
  "Ant-manning",
  "Groot-ing",
  "Gamora-ing",
  "Starlord-dancing",
  "Rocket-racooning",
  "Panther-prowling",
  "Strange-portaling",
  "Scarlet-witching",
  "Vision-phasing",
  "Hawkeye-aiming",
  "Avengers-assembling"
]

function StreamingIndicator({ streamKey, isThinking = false }) {
  // Pick a random phrase - use streamKey to ensure new phrase on each stream
  const phrase = useMemo(() => {
    const randomIndex = Math.floor(Math.random() * LOADING_PHRASES.length)
    return LOADING_PHRASES[randomIndex]
  }, [streamKey])

  // When thinking is active, show "Thinking..." instead of random phrases
  const displayText = isThinking ? 'Thinking' : phrase

  return (
    <div className="flex items-center gap-2 py-2">
      <div className="streaming-loader" />
      <span className="shimmer-text">{displayText}...</span>
    </div>
  )
}

export default StreamingIndicator
